name: Release
on:
  workflow_run:
    workflows: ['Pr']
    branches:
      - main
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Do Release
        run: echo 'Released!'